# Generated by Django 3.2.6 on 2021-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellVeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=20)),
                ('addr1', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
    ]
