# Generated by Django 3.2.6 on 2021-08-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_sellveg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='addr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='addr1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellveg',
            name='zip',
            field=models.TextField(),
        ),
    ]
